import "./globals.css";
import { Inter } from "next/font/google";
// Import Swiper styles
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";
import ReactQueryProviders from "@/providers/ReactQuerySetup/ReactQueryProviders";
import AllMoviesProvider from "@/providers/data/AllMoviesData";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "J4B Movies",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReactQueryProviders>
        <AllMoviesProvider>
          <body className={inter.className}>{children}</body>
        </AllMoviesProvider>
      </ReactQueryProviders>
    </html>
  );
}
