import { Inter } from "next/font/google";
// import ReactQueryProviders from "@/providers/ReactQuerySetup/ReactQueryProviders";
// import AllMoviesProvider from "@/providers/data/AllMoviesData";
// import SidebarNav from "@/components/dashboard/SidebarNav";
import { FaBell, FaChartBar, FaHome } from "react-icons/fa";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dashboard || J4B Movies",
  description: "Generated by create next app",
};


const menus = [
    {
      name: "Dashboard",
      path: "",
      icon: <FaHome width={18} className="text-blue-500" />,
      isActive: true,
    },
    {
      name: "Analytics",
      path: "/home",
      isActive: true,
      icon: <FaChartBar width={18} className="text-gray-600" />,
    },
    {
      name: "Notification",
      path: "home",
      isActive: false,
      icon: <FaBell width={18} className="text-gray-600" />,
    },
  ];

export default function DashboardLayout({ children }) {
  return (
    <html lang="en">
      {/* <ReactQueryProviders>
        <AllMoviesProvider> */}
      <body className={inter.className}>

      <div className="drawer lg:drawer-open">
        <input id="my-drawer-2" type="checkbox" className="drawer-toggle" />
        <div className="drawer-content flex flex-col items-center justify-center">
          {/* Page content here */}
          {children}
          <label
            htmlFor="my-drawer-2"
            className="btn btn-primary drawer-button lg:hidden"
          >
            Open drawer
          </label>
        </div>
        <div className="drawer-side">
          <label htmlFor="my-drawer-2" className="drawer-overlay"></label>
          <ul className="menu p-4 w-80 h-full bg-base-200 text-base-content">
            {/* Sidebar content here */}
            {menus.map((menu, index) => (
              <li key={index}>{menu.name}</li>
            ))}
          </ul>
        </div>
      </div>

     
      </body>
      {/* </AllMoviesProvider>
      </ReactQueryProviders> */}
    </html>
  );
}
