import { Inter } from "next/font/google";
// import ReactQueryProviders from "@/providers/ReactQuerySetup/ReactQueryProviders";
// import AllMoviesProvider from "@/providers/data/AllMoviesData";
// import SidebarLayout from "@/components/dashboard/SidebarLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dashboard || J4B Movies",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <html lang="en">
      {/* <ReactQueryProviders>
        <AllMoviesProvider> */}
          {/* <SidebarLayout> */}
            <body className={inter.className}>{children}</body>
          {/* </SidebarLayout> */}
        {/* </AllMoviesProvider>
      </ReactQueryProviders> */}
    </html>
  );
}